# REQUEST EXAMPLE
POST http://localhost:8000/api/v1/user/check-email/
Content-Type: application/json

{
"email": "test1@test.com"
}

# OBSERVATIONS:
# This function has a API limit defined
# it will start to fail after reaching the threshold

# POSSIBLE RESPONSE EXAMPLE:

## IN USE
# {
#     "message": "Email is already in use.",
#     "code": "IN_USE"
# }

## AVAILABLE
# {
#     "message": "Email is available.",
#     "code": "AVAILABLE"
# }