# REQUEST EXAMPLE
POST http://localhost:8000/api/v1/auth/jwt/refresh/
Content-Type: application/json

{
"refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcyNDcyMzI3NywiaWF0IjoxNzI0NjM2ODc3LCJqdGkiOiIzOGM4MmI5NjkxOTc0MWIzOWMyY2RmYzYyNDcxMTFlYSIsInVzZXJfaWQiOiI3NTdkNGZjZi1hZDRiLTQxZjktOTRlZS1lZmQ2MjI5NjdlZTMiLCJ1c2VyIjp7ImlkIjoiNzU3ZDRmY2YtYWQ0Yi00MWY5LTk0ZWUtZWZkNjIyOTY3ZWUzIiwidXNlcm5hbWUiOiJ0ZXN0MiIsImVtYWlsIjoidGVzdDJAdGVzdC5jb20iLCJwcm9maWxlX2ltYWdlX3VybCI6IiIsImRvYiI6bnVsbCwicGhvbmVfbnVtYmVyIjoiIiwiZGV2aWNlX2lkIjoiU2FtZUFzUmVnaXN0ZXJPck5ld09uZSIsImZpcnN0X25hbWUiOiIiLCJsYXN0X25hbWUiOiIiLCJpc19zdGFmZiI6ZmFsc2V9fQ.a4lVXG_jdNDUugVelVHe34a5e8kh9NqneFRhyctfDd8",
"device_id": "SameAsRegisterOrNewOne"
}

# OBSERVATIONS:
# refresh must be a valid refresh JWT token
# device_id must be the same as the one stored inside `refresh JWT token`
# This is the same thing as a quick logout and login,
# but instead of using password and username/email, it uses device_id and valid refresh token
# Old token will be blacklisted

# RESPONSE EXAMPLE:

# {
#   "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcyMzE0NDAwNCwiaWF0IjoxNzIzMDU3NjA0LCJqdGkiOiIwZTFhY2QwZmZiYTc0OGEwOTMwMjI4YTIyMzYzN2I3ZCIsInVzZXJfaWQiOiI5NzM3MTYwYS04YWZjLTRmNjAtYTNhOC1hYmUwNjE2MTMxOTYiLCJ1c2VyIjp7ImlkIjoiOTczNzE2MGEtOGFmYy00ZjYwLWEzYTgtYWJlMDYxNjEzMTk2IiwidXNlcm5hbWUiOiJ0ZXN0MSIsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsInByb2ZpbGVfaW1hZ2VfdXJsIjoiIiwiZG9iIjoiMTk5MC0wMS0wMSIsInBob25lX251bWJlciI6IisxMjM0NTY3ODkiLCJkZXZpY2VfaWQiOiJTYW1lQXNSZWdpc3Rlck9yTmV3T25lIiwiZmlyc3RfbmFtZSI6IiIsImxhc3RfbmFtZSI6IiIsImlzX3N0YWZmIjpmYWxzZX19.FA7LTDdRd9kRjjyz5v1oxQduq7lZoo5yaoohuVEpMwE",
#   "access": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIzMDU4ODA0LCJpYXQiOjE3MjMwNTc2MDQsImp0aSI6ImZlOTliYzY4MTM4YzRkMWY5Mjk5ZWRkMTNjN2NmMGFmIiwidXNlcl9pZCI6Ijk3MzcxNjBhLThhZmMtNGY2MC1hM2E4LWFiZTA2MTYxMzE5NiIsInVzZXIiOnsiaWQiOiI5NzM3MTYwYS04YWZjLTRmNjAtYTNhOC1hYmUwNjE2MTMxOTYiLCJ1c2VybmFtZSI6InRlc3QxIiwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwicHJvZmlsZV9pbWFnZV91cmwiOiIiLCJkb2IiOiIxOTkwLTAxLTAxIiwicGhvbmVfbnVtYmVyIjoiKzEyMzQ1Njc4OSIsImRldmljZV9pZCI6IlNhbWVBc1JlZ2lzdGVyT3JOZXdPbmUiLCJmaXJzdF9uYW1lIjoiIiwibGFzdF9uYW1lIjoiIiwiaXNfc3RhZmYiOmZhbHNlfX0.SLJvLgoFVeKr7kiuZS5cq2mC0VDgepqBcLts34sVoO0"
# }