# REQUEST EXAMPLE
POST http://localhost:8000/api/v1/auth/default/logout/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIzMDU4ODA0LCJpYXQiOjE3MjMwNTc2MDQsImp0aSI6ImZlOTliYzY4MTM4YzRkMWY5Mjk5ZWRkMTNjN2NmMGFmIiwidXNlcl9pZCI6Ijk3MzcxNjBhLThhZmMtNGY2MC1hM2E4LWFiZTA2MTYxMzE5NiIsInVzZXIiOnsiaWQiOiI5NzM3MTYwYS04YWZjLTRmNjAtYTNhOC1hYmUwNjE2MTMxOTYiLCJ1c2VybmFtZSI6InRlc3QxIiwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwicHJvZmlsZV9pbWFnZV91cmwiOiIiLCJkb2IiOiIxOTkwLTAxLTAxIiwicGhvbmVfbnVtYmVyIjoiKzEyMzQ1Njc4OSIsImRldmljZV9pZCI6IlNhbWVBc1JlZ2lzdGVyT3JOZXdPbmUiLCJmaXJzdF9uYW1lIjoiIiwibGFzdF9uYW1lIjoiIiwiaXNfc3RhZmYiOmZhbHNlfX0.SLJvLgoFVeKr7kiuZS5cq2mC0VDgepqBcLts34sVoO0

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcyMzE0NDAwNCwiaWF0IjoxNzIzMDU3NjA0LCJqdGkiOiIwZTFhY2QwZmZiYTc0OGEwOTMwMjI4YTIyMzYzN2I3ZCIsInVzZXJfaWQiOiI5NzM3MTYwYS04YWZjLTRmNjAtYTNhOC1hYmUwNjE2MTMxOTYiLCJ1c2VyIjp7ImlkIjoiOTczNzE2MGEtOGFmYy00ZjYwLWEzYTgtYWJlMDYxNjEzMTk2IiwidXNlcm5hbWUiOiJ0ZXN0MSIsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsInByb2ZpbGVfaW1hZ2VfdXJsIjoiIiwiZG9iIjoiMTk5MC0wMS0wMSIsInBob25lX251bWJlciI6IisxMjM0NTY3ODkiLCJkZXZpY2VfaWQiOiJTYW1lQXNSZWdpc3Rlck9yTmV3T25lIiwiZmlyc3RfbmFtZSI6IiIsImxhc3RfbmFtZSI6IiIsImlzX3N0YWZmIjpmYWxzZX19.FA7LTDdRd9kRjjyz5v1oxQduq7lZoo5yaoohuVEpMwE"
}

# OBSERVATIONS:
# access JTW token is required
# refresh JTW token in the body is required
# JWT will be blacklisted

# RESPONSE EXAMPLE:

# {
#   "detail": "Successfully logged out."
# }