# GET REQUEST EXAMPLE
GET http://localhost:8000/api/v1/auth/default/user/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIzMDU5NTU0LCJpYXQiOjE3MjMwNTgzNTQsImp0aSI6IjMwOGQyNDQxMDhhODRjNDI4MjJiYTU0MTFkYjM4NmRiIiwidXNlcl9pZCI6Ijk3MzcxNjBhLThhZmMtNGY2MC1hM2E4LWFiZTA2MTYxMzE5NiIsInVzZXIiOnsiaWQiOiI5NzM3MTYwYS04YWZjLTRmNjAtYTNhOC1hYmUwNjE2MTMxOTYiLCJ1c2VybmFtZSI6InRlc3QxIiwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwicHJvZmlsZV9pbWFnZV91cmwiOiIiLCJkb2IiOiIxOTkwLTAxLTAxIiwicGhvbmVfbnVtYmVyIjoiKzEyMzQ1Njc4OSIsImRldmljZV9pZCI6IlNhbWVBc1JlZ2lzdGVyT3JOZXdPbmUiLCJmaXJzdF9uYW1lIjoiIiwibGFzdF9uYW1lIjoiIiwiaXNfc3RhZmYiOmZhbHNlfX0.E56Apa4esn6hlii7OQ0iOwgOZgTNVhGrxZo2oMHTwIM

{}


# OBSERVATIONS:
# access JTW token is required
# this only gets user information

# RESPONSE EXAMPLE:

# {
#   "pk": "9737160a-8afc-4f60-a3a8-abe061613196",
#   "username": "test1",
#   "email": "test@test.com",
#   "first_name": "",
#   "last_name": ""
# }

### --------------------------------------------------------------------------
# PUT REQUEST EXAMPLE
PUT http://localhost:8000/api/v1/auth/default/user/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIzMDU5NTU0LCJpYXQiOjE3MjMwNTgzNTQsImp0aSI6IjMwOGQyNDQxMDhhODRjNDI4MjJiYTU0MTFkYjM4NmRiIiwidXNlcl9pZCI6Ijk3MzcxNjBhLThhZmMtNGY2MC1hM2E4LWFiZTA2MTYxMzE5NiIsInVzZXIiOnsiaWQiOiI5NzM3MTYwYS04YWZjLTRmNjAtYTNhOC1hYmUwNjE2MTMxOTYiLCJ1c2VybmFtZSI6InRlc3QxIiwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwicHJvZmlsZV9pbWFnZV91cmwiOiIiLCJkb2IiOiIxOTkwLTAxLTAxIiwicGhvbmVfbnVtYmVyIjoiKzEyMzQ1Njc4OSIsImRldmljZV9pZCI6IlNhbWVBc1JlZ2lzdGVyT3JOZXdPbmUiLCJmaXJzdF9uYW1lIjoiIiwibGFzdF9uYW1lIjoiIiwiaXNfc3RhZmYiOmZhbHNlfX0.E56Apa4esn6hlii7OQ0iOwgOZgTNVhGrxZo2oMHTwIM

{
  "pk": "9737160a-8afc-4f60-a3a8-abe061613196",
  "username": "test11",
  "email": "test@test.com",
  "first_name": "newFName",
  "last_name": "newLName"
}

# OBSERVATIONS:
# access JTW token is required
# this MUST contain the whole user information MODEL
# not recommended since it requires a new unique username

# RESPONSE EXAMPLE:

# {
#   "pk": "9737160a-8afc-4f60-a3a8-abe061613196",
#   "username": "test11",
#   "email": "test@test.com",
#   "first_name": "newFName",
#   "last_name": "newLName"
# }

### --------------------------------------------------------------------------
# PATCH REQUEST EXAMPLE
PATCH  http://localhost:8000/api/v1/auth/default/user/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIzMDU5NTU0LCJpYXQiOjE3MjMwNTgzNTQsImp0aSI6IjMwOGQyNDQxMDhhODRjNDI4MjJiYTU0MTFkYjM4NmRiIiwidXNlcl9pZCI6Ijk3MzcxNjBhLThhZmMtNGY2MC1hM2E4LWFiZTA2MTYxMzE5NiIsInVzZXIiOnsiaWQiOiI5NzM3MTYwYS04YWZjLTRmNjAtYTNhOC1hYmUwNjE2MTMxOTYiLCJ1c2VybmFtZSI6InRlc3QxIiwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwicHJvZmlsZV9pbWFnZV91cmwiOiIiLCJkb2IiOiIxOTkwLTAxLTAxIiwicGhvbmVfbnVtYmVyIjoiKzEyMzQ1Njc4OSIsImRldmljZV9pZCI6IlNhbWVBc1JlZ2lzdGVyT3JOZXdPbmUiLCJmaXJzdF9uYW1lIjoiIiwibGFzdF9uYW1lIjoiIiwiaXNfc3RhZmYiOmZhbHNlfX0.E56Apa4esn6hlii7OQ0iOwgOZgTNVhGrxZo2oMHTwIM

{
  "first_name": "newFName111",
  "last_name": "newLName222"
}

# OBSERVATIONS:
# access JTW token is required
# Update partial information from the user

# RESPONSE EXAMPLE:

# {
#   "pk": "9737160a-8afc-4f60-a3a8-abe061613196",
#   "username": "test11",
#   "email": "test@test.com",
#   "first_name": "newFName111",
#   "last_name": "newLName222"
# }