# POST REQUEST EXAMPLE
POST http://localhost:8000/api/v1/auth/default/password/change/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzI3MjYyMTI0LCJpYXQiOjE3MjcyNjE1MjQsImp0aSI6ImQzYzI4MDhjZjhiMzQyMzNhN2JjNTg2ZTMzN2FkNWRhIiwidXNlcl9pZCI6IjJhYjc4OWU2LTZkM2ItNGY1OS1iZjUwLTUyOGY1NWVlYjljNyIsInVzZXIiOnsiaWQiOiIyYWI3ODllNi02ZDNiLTRmNTktYmY1MC01MjhmNTVlZWI5YzciLCJ1c2VybmFtZSI6InRlc3QxIiwiZW1haWwiOiJ0ZXN0MUB0ZXN0LmNvbSIsInByb2ZpbGVfaW1hZ2VfdXJsIjoiIiwiZG9iIjpudWxsLCJwaG9uZV9udW1iZXIiOiIiLCJkZXZpY2VfaWQiOiJTYW1lQXNSZWdpc3Rlck9yTmV3T25lIiwiZmlyc3RfbmFtZSI6IkpvaG4iLCJsYXN0X25hbWUiOiJTbW90aGVyIiwiaXNfc3RhZmYiOmZhbHNlfX0.vc9daNeN8RidT6SIQkvVQePumU_JVrOn4aSNLs6hxDM

{
    "new_password1": "Pass123!@##",
    "new_password2": "Pass123!@##"
}

# OBSERVATIONS:
# N/A

# RESPONSE EXAMPLE:

# {
#   "detail": "New password has been saved."
# }
