# REQUEST EXAMPLE
POST http://localhost:8000/api/v1/auth/default/token/refresh/
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcyMzE0NDc1NCwiaWF0IjoxNzIzMDU4MzU0LCJqdGkiOiI5NGM5YWViNzNkMjQ0ODEyOGMyYWQyNmZmMDc5YzFhZiIsInVzZXJfaWQiOiI5NzM3MTYwYS04YWZjLTRmNjAtYTNhOC1hYmUwNjE2MTMxOTYiLCJ1c2VyIjp7ImlkIjoiOTczNzE2MGEtOGFmYy00ZjYwLWEzYTgtYWJlMDYxNjEzMTk2IiwidXNlcm5hbWUiOiJ0ZXN0MSIsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsInByb2ZpbGVfaW1hZ2VfdXJsIjoiIiwiZG9iIjoiMTk5MC0wMS0wMSIsInBob25lX251bWJlciI6IisxMjM0NTY3ODkiLCJkZXZpY2VfaWQiOiJTYW1lQXNSZWdpc3Rlck9yTmV3T25lIiwiZmlyc3RfbmFtZSI6IiIsImxhc3RfbmFtZSI6IiIsImlzX3N0YWZmIjpmYWxzZX19.xL_fuLMEyac6h2PGf3tKuxCCXsI2Bh0HNhsjWLM6avk"
}

# OBSERVATIONS:
# valid refresh token is required
# this only refreses the access token

# RESPONSE EXAMPLE:

# {
#   "access": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIzMDYwMjk0LCJpYXQiOjE3MjMwNTgzNTQsImp0aSI6ImE1YmMxZDc1YTMxMzQ5MmY5ZjM3ZjUzNGQ5OWNmZjIyIiwidXNlcl9pZCI6Ijk3MzcxNjBhLThhZmMtNGY2MC1hM2E4LWFiZTA2MTYxMzE5NiIsInVzZXIiOnsiaWQiOiI5NzM3MTYwYS04YWZjLTRmNjAtYTNhOC1hYmUwNjE2MTMxOTYiLCJ1c2VybmFtZSI6InRlc3QxIiwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwicHJvZmlsZV9pbWFnZV91cmwiOiIiLCJkb2IiOiIxOTkwLTAxLTAxIiwicGhvbmVfbnVtYmVyIjoiKzEyMzQ1Njc4OSIsImRldmljZV9pZCI6IlNhbWVBc1JlZ2lzdGVyT3JOZXdPbmUiLCJmaXJzdF9uYW1lIjoiIiwibGFzdF9uYW1lIjoiIiwiaXNfc3RhZmYiOmZhbHNlfX0.7w2RzqS4NLXuTL27GcouLrrNTdJkuf2lSCjJNDqif-c",
#   "access_expiration": "2024-08-07T19:51:34.620635Z"
# }